export const blue = '#b6ffff';
export const gray = '#e5e5e5';
export const red = '#ff7272';

export const dataTemplate1 = [
    { key: 0, text: "Template 2" },
    {
      key: 1,
      parent: 0,
      estimatedDuration: 100000,
      text: "Updates",
      node: true,
      active: "true",
    },
    {
      key: 11,
      parent: 1,
      estimatedDuration: 470000,
      text: "News and announcements",
      node: true,
      active: "false",
    },
    {
      key: 111,
      parent: 11,
      estimatedDuration: 500000,
      text: "Woke up late template 2",
      node: false,
    },
    {
      key: 112,
      parent: 11,
      estimatedDuration: 500000,
      text: "Skipped breakfast template 2",
      node: false,
    },
    {
      key: 113,
      parent: 11,
      estimatedDuration: 600000,
      text: "Going to be late template 2",
      node: false,
      type: "custom",
    },
    {
      key: 12,
      parent: 1,
      estimatedDuration: 50000,
      text: "Delegate",
      node: true,
      active: "false",
    },
    {
      key: 13,
      parent: 1,
      estimatedDuration: 50000,
      text: "Simplify",
      node: true,
      active: "false",
    },
    {
      key: 2,
      parent: 0,
      estimatedDuration: 50000,
      text: "More effective use",
      node: true,
      active: "false",
    },
    {
      key: 21,
      parent: 2,
      estimatedDuration: 50000,
      text: "Planning",
      node: true,
      active: "false",
    },
    {
      key: 211,
      parent: 21,
      estimatedDuration: 50000,
      text: "Priorities",
      node: true,
      active: "false",
    },
    {
      key: 212,
      parent: 21,
      estimatedDuration: 50000,
      text: "Ways to focus",
      node: true,
      active: "false",
    },
    {
      key: 22,
      parent: 2,
      estimatedDuration: 50000,
      text: "Goals",
      node: true,
      active: "false",
    },
  ];
  export const dataTemplate2 = [
    { key: 0, text: "Template 3" },
    {
      key: 1,
      parent: 0,
      estimatedDuration: 50000,
      text: "template 2 text",
      node: true,
      active: "true",
    },
    {
      key: 11,
      parent: 1,
      estimatedDuration: 470000,
      text: "Wake up early template 3",
      node: true,
      active: "false",
    },
    {
      key: 111,
      parent: 11,
      estimatedDuration: 500000,
      text: "Woke up late template 3",
      node: false,
    },
    {
      key: 112,
      parent: 11,
      estimatedDuration: 500000,
      text: "Skipped breakfast template 3",
      node: false,
    },
    {
      key: 113,
      parent: 11,
      estimatedDuration: 600000,
      text: "Going to be late template 3",
      node: false,
      type: "custom",
    },
    {
      key: 12,
      parent: 1,
      estimatedDuration: 50000,
      text: "Delegate",
      node: true,
      active: "false",
    },
    {
      key: 13,
      parent: 1,
      estimatedDuration: 50000,
      text: "Simplify",
      node: true,
      active: "false",
    },
    {
      key: 2,
      parent: 0,
      estimatedDuration: 50000,
      text: "More effective use",
      node: true,
      active: "false",
    },
    {
      key: 21,
      parent: 2,
      estimatedDuration: 50000,
      text: "Planning",
      node: true,
      active: "false",
    },
    {
      key: 211,
      parent: 21,
      estimatedDuration: 50000,
      text: "Priorities",
      node: true,
      active: "false",
    },
    {
      key: 212,
      parent: 21,
      estimatedDuration: 50000,
      text: "Ways to focus",
      node: true,
      active: "false",
    },
    {
      key: 22,
      parent: 2,
      estimatedDuration: 50000,
      text: "Goals",
      node: true,
      active: "false",
    },
  ];
  export const dataTemplate3 = [
    { key: 0, text: "Weekly Team Meeting" },
    {
      key: 1,
      parent: 0,
      estimatedDuration:  5 * 60 * 100000,
      text: "Updates",
      node: true,
      active: "true",
    },
    {
      key: 11,
      parent: 1,
      estimatedDuration: 470000,
      text: "News and announcements",
      node: false,
      active: "false",
    },
    {
      key: 2,
      parent: 0,
      estimatedDuration:  5 * 60 * 100000,
      text: "Big Picture",
      node: true,
      active: "false",
    },
    {
      key: 21,
      parent: 2,
      estimatedDuration: 50000,
      text: "Where are we relative to our goals?",
      node: false,
      active: "false",
    },
    {
      key: 3,
      parent: 0,
      estimatedDuration:  5 * 60 * 100000,
      text: "Priorities",
      node: true,
      active: "false",
    },
    {
      key: 31,
      parent: 3,
      estimatedDuration: 50000,
      text: "What will everyone's main focus be this week?",
      node: false,
      active: "false",
    },
    {
      key: 4,
      parent: 0,
      estimatedDuration:  5 * 60 * 100000,
      text: "Roadblocks",
      node: true,
      active: "false",
    },
    {
      key: 41,
      parent: 4,
      estimatedDuration: 50000,
      text: "Any challenges/concerns?",
      node: false,
      active: "false",
    },
    {
      key: 5,
      parent: 0,
      estimatedDuration:  5 * 60 * 100000,
      text: "Action Items",
      node: true,
      active: "false",
    },
    {
      key: 51,
      parent: 5,
      estimatedDuration: 50000,
      text: "What are the next steps related to this meeting?",
      node: false,
      active: "false",
    },
  ];
  export const dataTemplate4 = [
    { key: 0, text: "Sales Team Meeting" },
    {
      key: 1,
      parent: 0,
      estimatedDuration:  100000,
      text: "Metrics Review",
      node: true,
      active: "true",
    },
    {
      key: 11,
      parent: 1,
      estimatedDuration: 470000,
      text: "Opportunnities",
      node: false,
      active: "false",
    },
    {
      key: 2,
      parent: 0,
      estimatedDuration:  100000,
      text: "Updates",
      node: true,
      active: "false",
    },
    {
      key: 21,
      parent: 2,
      estimatedDuration: 50000,
      text: "    1. Deals, channel updates, and new opportunities",
      node: false,
      active: "false",
    },
    {
      key: 3,
      parent: 0,
      estimatedDuration:  100000,
      text: "Roadblocks",
      node: true,
      active: "false",
    },
    {
      key: 31,
      parent: 3,
      estimatedDuration: 50000,
      text: "Any challenges/concerns?",
      node: false,
      active: "false",
    },
    {
      key: 4,
      parent: 0,
      estimatedDuration:  100000,
      text: "Action Items",
      node: true,
      active: "false",
    },
    {
      key: 41,
      parent: 4,
      estimatedDuration: 50000,
      text: "What are the next steps related to this meeting?",
      node: false,
      active: "false",
    },
  ];
  export const dataTemplate5 = [
    { key: 0, text: " Project Kick-off Meeting" },
    {
      key: 1,
      parent: 0,
      estimatedDuration:  100000,
      text: "Background & Purpose",
      node: true,
      active: "true",
    },
    {
      key: 11,
      parent: 1,
      estimatedDuration: 470000,
      text: "Context and goals of the project",
      node: false,
      active: "false",
    },
    {
      key: 2,
      parent: 0,
      estimatedDuration: 100000,
      text: "Timeline",
      node: true,
      active: "false",
    },
    {
      key: 21,
      parent: 2,
      estimatedDuration: 50000,
      text: "Timeline of the project",
      node: false,
      active: "false",
    },
    {
      key: 3,
      parent: 0,
      estimatedDuration:  100000,
      text: "Scope",
      node: true,
      active: "false",
    },
    {
      key: 31,
      parent: 3,
      estimatedDuration: 50000,
      text: "What needs to be done?",
      node: false,
      active: "false",
    },
    {
      key: 4,
      parent: 0,
      estimatedDuration:  100000,
      text: "Roles",
      node: true,
      active: "false",
    },
    {
      key: 41,
      parent: 4,
      estimatedDuration: 50000,
      text: "Who is in charge?",
      node: false,
      active: "false",
    },
    {
      key: 5,
      parent: 0,
      estimatedDuration:  100000,
      text: "Action Items",
      node: true,
      active: "false",
    },
    {
      key: 51,
      parent: 5,
      estimatedDuration: 50000,
      text: "What are the next steps related to this meeting?",
      node: false,
      active: "false",
    },
  ];
  export const NewTemplate = [{ key: 0, text: "New Agenda" }];
